### ISSUE TITLE
[spec] `privateAggregationConfig` is missing in the `SharedStorageRunOperationMethodOptions` dictionary

### ISSUE THREAD

**Issue by pythagoraskitty** [WICG/shared-storage#175]
The currently implemented `SharedStorageRunOperationMethodOptions` IDL dictionary in Chromium is:

```
dictionary SharedStorageRunOperationMethodOptions {
  object data;
  boolean resolveToConfig = false;
  boolean keepAlive = false;
  SharedStoragePrivateAggregationConfig privateAggregationConfig;
};
```

In particular, it looks like we have not yet updated the spec to include `privateAggregationConfig`.

**Comment by alexmturner** [comment]
This is because this part of the spec is a monkey patch in Private Aggregation's spec (see [here](https://patcg-individual-drafts.github.io/private-aggregation-api/#shared-storage-api-monkey-patches)). However, we should definitely move it over!

I've been working to do that, should hopefully have it up for review soon.
